DROP TABLE IF EXISTS records;

CREATE TABLE records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    video TEXT NOT NULL,
    time_slot INTEGER NOT NULL,
    concept TEXT NOT NULL,
    name TEXT NOT NULL,
    link TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
